# Generated by Django 4.1.4 on 2023-01-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_order1'),
    ]

    operations = [
        migrations.AddField(
            model_name='order1',
            name='total',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
